name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  packages: read
  contents: write

env:
  # FIXME: For some reason bun:latest breaks package installs, so it's 1.0.7 for now
  BUN_VERSION: "1.0.7"
  IS_PRERELEASE: "${{contains(github.ref_name, 'dev')}}"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "${{env.BUN_VERSION}}"

      - run: bun install --frozen-lockfile
      - run: bun run build

      - uses: actions/upload-artifact@v3
        with:
          path: build/*

  build-macos:
    runs-on: macos-latest

    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "${{env.BUN_VERSION}}"

      - run: bun install --frozen-lockfile
      - run: bun run build

      - uses: actions/upload-artifact@v3
        with:
          path: build/*

  publish:
    needs:
      - build-linux
      - build-macos

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: artifacts/*/*
          prerelease: ${{env.IS_PRERELEASE}}
