name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  packages: read
  contents: write

env:
  IS_PRERELEASE: "${{contains(github.ref_name, 'dev')}}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "^9.15.4"
      - uses: actions/setup-node@v3
        with:
          node-version: ">=21.0.0"
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: |
          pnpm install --frozen-lockfile
          pnpm build

      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: build/bin/*
          prerelease: ${{env.IS_PRERELEASE}}
