name: release-binary

on:
  push:
    tags:
      - "v*"

permissions:
  packages: read
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run build

      - uses: actions/upload-artifact@v3
        with:
          path: build/*

  build-macos:
    runs-on: macos-latest

    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run build

      - uses: actions/upload-artifact@v3
        with:
          path: build/*

  publish:
    needs:
      - build-linux
      - build-macos

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: artifacts/*/*
