name: release-binary

on:
  push:
    tags:
      - "v*"

permissions:
  packages: read
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run compile

      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: build/s21
