name: relase-binary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun run compile

      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: build/s21
